// ---------------------------------------------------------------------------
// ASR Replication Policy generator – produces Bicep for Azure Site Recovery
// ---------------------------------------------------------------------------
import { AnalysisResult, GeneratedArtifact } from '../models/types';
import { getRegionDisplayName } from '../utils/regionPairs';
import { API_VERSIONS } from '../utils/constants';

export function generateAsrPolicy(analysis: AnalysisResult): GeneratedArtifact | undefined {
    // ASR is primarily for IaaS VMs
    const vmWorkload = analysis.workloads.find(w => w.type === 'IaaS-VM');
    if (!vmWorkload) { return undefined; }

    const primary = analysis.primaryRegion;
    const secondary = analysis.pairedRegion;
    const primaryDisplay = getRegionDisplayName(primary);
    const secondaryDisplay = getRegionDisplayName(secondary);
    const rpo = vmWorkload.recommendedRpoMinutes;
    const apiVer = API_VERSIONS.recoveryServicesVault;

    const bicep = `// ---------------------------------------------------------------------------
// Azure Site Recovery – Replication Policy & Vault
// Generated by Azure DR Blueprint Generator
// Primary Region: ${primaryDisplay} → DR Region: ${secondaryDisplay}
// ---------------------------------------------------------------------------

@description('Primary region for the workload')
param primaryLocation string = '${primary}'

@description('DR region (Azure paired region)')
param drLocation string = '${secondary}'

@description('Name prefix for DR resources')
param namePrefix string = 'dr'

@description('Recovery Point Objective in minutes')
param rpoInMinutes int = ${rpo}

@description('Application-consistent snapshot frequency in minutes (60 = hourly)')
param appConsistentFrequencyInMinutes int = 60

@description('Recovery point retention in hours')
param recoveryPointRetentionInHours int = 24

// ---------------------------------------------------------------------------
// Recovery Services Vault in the DR region
// ---------------------------------------------------------------------------
resource recoveryVault 'Microsoft.RecoveryServices/vaults@${apiVer}' = {
  name: '\${namePrefix}-rsv-\${drLocation}'
  location: drLocation
  sku: {
    name: 'RS0'
    tier: 'Standard'
  }
  properties: {
    publicNetworkAccess: 'Enabled'
  }
}

// ---------------------------------------------------------------------------
// Replication Policy – controls RPO, snapshot frequency, retention
// ---------------------------------------------------------------------------
resource replicationPolicy 'Microsoft.RecoveryServices/vaults/replicationPolicies@${apiVer}' = {
  parent: recoveryVault
  name: '\${namePrefix}-replication-policy'
  properties: {
    providerSpecificInput: {
      instanceType: 'A2A'
      multiVmSyncStatus: 'Enable'
      recoveryPointHistory: recoveryPointRetentionInHours * 60  // convert to minutes
      appConsistentFrequencyInMinutes: appConsistentFrequencyInMinutes
      crashConsistentFrequencyInMinutes: rpoInMinutes
    }
  }
}

// ---------------------------------------------------------------------------
// Replication Fabric – represents the primary region
// ---------------------------------------------------------------------------
resource primaryFabric 'Microsoft.RecoveryServices/vaults/replicationFabrics@${apiVer}' = {
  parent: recoveryVault
  name: '\${namePrefix}-fabric-\${primaryLocation}'
  properties: {
    customDetails: {
      instanceType: 'Azure'
      location: primaryLocation
    }
  }
}

// ---------------------------------------------------------------------------
// Replication Fabric – represents the DR region
// ---------------------------------------------------------------------------
resource drFabric 'Microsoft.RecoveryServices/vaults/replicationFabrics@${apiVer}' = {
  parent: recoveryVault
  name: '\${namePrefix}-fabric-\${drLocation}'
  properties: {
    customDetails: {
      instanceType: 'Azure'
      location: drLocation
    }
  }
}

// ---------------------------------------------------------------------------
// Protection Container in primary fabric
// ---------------------------------------------------------------------------
resource primaryContainer 'Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers@${apiVer}' = {
  parent: primaryFabric
  name: '\${namePrefix}-container-\${primaryLocation}'
  properties: {}
}

// ---------------------------------------------------------------------------
// Protection Container in DR fabric
// ---------------------------------------------------------------------------
resource drContainer 'Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers@${apiVer}' = {
  parent: drFabric
  name: '\${namePrefix}-container-\${drLocation}'
  properties: {}
}

// ---------------------------------------------------------------------------
// Container Mapping – links primary → DR using the replication policy
// ---------------------------------------------------------------------------
resource containerMapping 'Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers/replicationProtectionContainerMappings@${apiVer}' = {
  parent: primaryContainer
  name: '\${namePrefix}-mapping-\${primaryLocation}-to-\${drLocation}'
  properties: {
    targetProtectionContainerId: drContainer.id
    policyId: replicationPolicy.id
    providerSpecificInput: {
      instanceType: 'A2A'
    }
  }
}

// ---------------------------------------------------------------------------
// Outputs
// ---------------------------------------------------------------------------
output recoveryVaultId string = recoveryVault.id
output recoveryVaultName string = recoveryVault.name
output replicationPolicyId string = replicationPolicy.id
output primaryFabricId string = primaryFabric.id
output drFabricId string = drFabric.id
`;

    return {
        relativePath: 'asr-replication-policy.bicep',
        content: bicep,
        description: `ASR replication policy: ${primaryDisplay} → ${secondaryDisplay}, RPO ${rpo} min`,
    };
}
