// ---------------------------------------------------------------------------
// DR Test Scheduler – generates a PowerShell script for isolated test failovers
// ---------------------------------------------------------------------------
import { AnalysisResult, GeneratedArtifact } from '../models/types';
import { getRegionDisplayName } from '../utils/regionPairs';

export function generateTestScheduler(
    analysis: AnalysisResult,
    cronExpression: string,
): GeneratedArtifact {
    const primary = analysis.primaryRegion;
    const secondary = analysis.pairedRegion;
    const primaryDisplay = getRegionDisplayName(primary);
    const secondaryDisplay = getRegionDisplayName(secondary);

    const hasVMs = analysis.workloads.some(w => w.type === 'IaaS-VM');

    const ps1 = `<#
.SYNOPSIS
    Azure DR Test Scheduler – Isolated Test Failover with Automatic Cleanup
    Generated by Azure DR Blueprint Generator

.DESCRIPTION
    Creates an isolated test failover in ${secondaryDisplay} to validate DR readiness.
    This script:
    ${hasVMs ? '- Initiates ASR test failover (creates resources in isolated VNet)\n    ' : ''}- Runs health checks against the test environment
    - Generates a test result report
    - Cleans up all test failover resources automatically
    - Designed to run on a schedule (cron: ${cronExpression})

    Schedule this script using:
    - Azure Automation Runbook with a recurring schedule
    - Windows Task Scheduler
    - Linux cron job

.PARAMETER DrResourceGroupName
    Resource group containing DR/Recovery Services resources.

.PARAMETER RecoveryVaultName
    Name of the Recovery Services Vault with ASR replication.

.PARAMETER TestVNetId
    Resource ID of the isolated VNet for test failover. This VNet should NOT
    be connected to production networks.

.PARAMETER NotificationEmail
    Email address to send test results (requires SendGrid or SMTP relay).

.EXAMPLE
    .\\dr-test-scheduler.ps1 \\
        -DrResourceGroupName "rg-dr-${secondary}" \\
        -RecoveryVaultName "dr-rsv-${secondary}" \\
        -TestVNetId "/subscriptions/<sub-id>/resourceGroups/rg-dr-test/providers/Microsoft.Network/virtualNetworks/vnet-dr-test"

.NOTES
    Recommended schedule: ${cronExpression} (quarterly on the 1st at 2 AM UTC)
    Azure Automation schedule equivalent: Monthly on Day 1, every 3 months
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [string]$DrResourceGroupName,

    [Parameter(Mandatory=$true)]
    [string]$RecoveryVaultName,

    [Parameter(Mandatory=$true)]
    [string]$TestVNetId,

    [Parameter(Mandatory=$false)]
    [string]$NotificationEmail,

    [Parameter(Mandatory=$false)]
    [int]$TestTimeoutMinutes = 90,

    [Parameter(Mandatory=$false)]
    [int]$CleanupDelayMinutes = 30
)

$ErrorActionPreference = "Stop"
$script:testResults = @()
$script:startTime = Get-Date
$reportFile = "dr-test-report-$(Get-Date -Format 'yyyyMMdd-HHmmss').md"

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host "[$timestamp] [$Level] $Message"
}

function Add-TestResult {
    param(
        [string]$TestName,
        [string]$Status,
        [string]$Details
    )
    $script:testResults += [PSCustomObject]@{
        TestName = $TestName
        Status   = $Status
        Details  = $Details
        Time     = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    }
}

# ═══════════════════════════════════════════════════════════════════════════
# Connect & Validate
# ═══════════════════════════════════════════════════════════════════════════
Write-Log "============================================="
Write-Log "Azure DR Test Failover – Starting"
Write-Log "Primary Region:   ${primaryDisplay}"
Write-Log "DR Region:        ${secondaryDisplay}"
Write-Log "Schedule (cron):  ${cronExpression}"
Write-Log "============================================="

try {
    $context = Get-AzContext
    if (-not $context) {
        Connect-AzAccount -Identity  # Use managed identity in Azure Automation
    }
    Write-Log "Connected as: $($context.Account.Id)"
    Add-TestResult -TestName "Azure Authentication" -Status "PASS" -Details "Connected successfully"
} catch {
    Add-TestResult -TestName "Azure Authentication" -Status "FAIL" -Details "$_"
    Write-Log "FATAL: Cannot authenticate: $_" -Level "ERROR"
    exit 1
}

# ═══════════════════════════════════════════════════════════════════════════
# Pre-flight Checks
# ═══════════════════════════════════════════════════════════════════════════
Write-Log "Running pre-flight checks..."

# Check DR resource group
$rg = Get-AzResourceGroup -Name $DrResourceGroupName -ErrorAction SilentlyContinue
if ($rg) {
    Add-TestResult -TestName "DR Resource Group Exists" -Status "PASS" -Details $DrResourceGroupName
} else {
    Add-TestResult -TestName "DR Resource Group Exists" -Status "FAIL" -Details "Not found: $DrResourceGroupName"
    exit 1
}

# Check Recovery Vault
try {
    $vault = Get-AzRecoveryServicesVault -ResourceGroupName $DrResourceGroupName -Name $RecoveryVaultName
    Set-AzRecoveryServicesAsrVaultContext -Vault $vault
    Add-TestResult -TestName "Recovery Vault Accessible" -Status "PASS" -Details $RecoveryVaultName
} catch {
    Add-TestResult -TestName "Recovery Vault Accessible" -Status "FAIL" -Details "$_"
    exit 1
}

# Check replication health
$fabric = Get-AzRecoveryServicesAsrFabric | Where-Object { $_.FriendlyName -like "*${primary}*" }
$container = Get-AzRecoveryServicesAsrProtectionContainer -Fabric $fabric
$protectedItems = Get-AzRecoveryServicesAsrReplicationProtectedItem -ProtectionContainer $container

Write-Log "Found $($protectedItems.Count) protected item(s)"

foreach ($item in $protectedItems) {
    $health = $item.ReplicationHealth
    $status = if ($health -eq "Normal") { "PASS" } else { "WARN" }
    Add-TestResult -TestName "Replication Health: $($item.FriendlyName)" -Status $status -Details "Health: $health"
}

# ═══════════════════════════════════════════════════════════════════════════
# Test Failover (Isolated)
# ═══════════════════════════════════════════════════════════════════════════
Write-Log ""
Write-Log "Initiating TEST failover (isolated – no production impact)..."
$testFailoverJobs = @()

foreach ($item in $protectedItems) {
    Write-Log "  Starting test failover for: $($item.FriendlyName)"
    try {
        $job = Start-AzRecoveryServicesAsrTestFailoverJob \`
            -ReplicationProtectedItem $item \`
            -Direction PrimaryToRecovery \`
            -AzureVMNetworkId $TestVNetId

        $testFailoverJobs += @{ Item = $item; Job = $job }
        Add-TestResult -TestName "Test Failover Started: $($item.FriendlyName)" -Status "PASS" -Details "Job: $($job.Name)"
    } catch {
        Add-TestResult -TestName "Test Failover Started: $($item.FriendlyName)" -Status "FAIL" -Details "$_"
    }
}

# Wait for all test failovers to complete
Write-Log "Waiting for test failovers to complete (timeout: $TestTimeoutMinutes min)..."
$deadline = (Get-Date).AddMinutes($TestTimeoutMinutes)

foreach ($entry in $testFailoverJobs) {
    $remainingSeconds = ($deadline - (Get-Date)).TotalSeconds
    if ($remainingSeconds -le 0) {
        Add-TestResult -TestName "Test Failover Complete: $($entry.Item.FriendlyName)" -Status "FAIL" -Details "Timeout"
        continue
    }
    try {
        $completedJob = Get-AzRecoveryServicesAsrJob -Job $entry.Job |
            Wait-AzRecoveryServicesAsrJob -WaitTimeInSeconds ([int]$remainingSeconds)

        $status = if ($completedJob.State -eq "Succeeded") { "PASS" } else { "FAIL" }
        Add-TestResult -TestName "Test Failover Complete: $($entry.Item.FriendlyName)" -Status $status -Details "State: $($completedJob.State)"
    } catch {
        Add-TestResult -TestName "Test Failover Complete: $($entry.Item.FriendlyName)" -Status "FAIL" -Details "$_"
    }
}

# ═══════════════════════════════════════════════════════════════════════════
# Post-Failover Health Checks
# ═══════════════════════════════════════════════════════════════════════════
Write-Log ""
Write-Log "Running post-failover health checks..."
Write-Log "  Waiting $CleanupDelayMinutes minutes for VMs to stabilize..."
Start-Sleep -Seconds ($CleanupDelayMinutes * 60)

# Check that test VMs are running
$testVMs = Get-AzVM -ResourceGroupName $DrResourceGroupName -Status |
    Where-Object { $_.Name -like "*-test*" -or $_.Name -like "*asr*" }

foreach ($vm in $testVMs) {
    $powerState = ($vm.Statuses | Where-Object { $_.Code -like "PowerState/*" }).DisplayStatus
    $status = if ($powerState -eq "VM running") { "PASS" } else { "FAIL" }
    Add-TestResult -TestName "Test VM Running: $($vm.Name)" -Status $status -Details $powerState
}

# ═══════════════════════════════════════════════════════════════════════════
# Cleanup Test Failover
# ═══════════════════════════════════════════════════════════════════════════
Write-Log ""
Write-Log "Cleaning up test failover resources..."

foreach ($entry in $testFailoverJobs) {
    try {
        $cleanupJob = Start-AzRecoveryServicesAsrTestFailoverCleanupJob \`
            -ReplicationProtectedItem $entry.Item \`
            -Comment "Automated DR test completed at $(Get-Date -Format 'yyyy-MM-dd HH:mm')"

        $null = Get-AzRecoveryServicesAsrJob -Job $cleanupJob | Wait-AzRecoveryServicesAsrJob
        Add-TestResult -TestName "Cleanup: $($entry.Item.FriendlyName)" -Status "PASS" -Details "Cleaned up"
    } catch {
        Add-TestResult -TestName "Cleanup: $($entry.Item.FriendlyName)" -Status "FAIL" -Details "$_"
    }
}

# ═══════════════════════════════════════════════════════════════════════════
# Generate Test Report (Markdown)
# ═══════════════════════════════════════════════════════════════════════════
$duration = (Get-Date) - $script:startTime
$passCount = ($script:testResults | Where-Object { $_.Status -eq "PASS" }).Count
$failCount = ($script:testResults | Where-Object { $_.Status -eq "FAIL" }).Count
$warnCount = ($script:testResults | Where-Object { $_.Status -eq "WARN" }).Count
$overallStatus = if ($failCount -eq 0) { "PASSED" } else { "FAILED" }

$report = @"
# DR Test Failover Report

| Field | Value |
|-------|-------|
| **Date** | $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC') |
| **Primary Region** | ${primaryDisplay} |
| **DR Region** | ${secondaryDisplay} |
| **Duration** | $($duration.ToString('hh\:mm\:ss')) |
| **Overall Result** | **$overallStatus** |
| **Tests Passed** | $passCount |
| **Tests Failed** | $failCount |
| **Warnings** | $warnCount |

## Test Results

| # | Test | Status | Details | Time |
|---|------|--------|---------|------|
"@

$i = 1
foreach ($result in $script:testResults) {
    $icon = switch ($result.Status) { "PASS" { "✅" } "FAIL" { "❌" } "WARN" { "⚠️" } }
    $report += "| $i | $($result.TestName) | $icon $($result.Status) | $($result.Details) | $($result.Time) |" + [Environment]::NewLine
    $i++
}

$report += @'

## Next Scheduled Test

Cron: ` + "`" + `${cronExpression}` + "`" + ` (Quarterly on the 1st at 2:00 AM UTC)

---
*Generated by Azure DR Blueprint Generator*
'@

Set-Content -Path $reportFile -Value $report -Encoding UTF8
Write-Log ""
Write-Log "============================================="
Write-Log "DR TEST COMPLETE: $overallStatus"
Write-Log "Report saved to: $reportFile"
Write-Log "============================================="
`;

    return {
        relativePath: 'dr-test-scheduler.ps1',
        content: ps1,
        description: `DR test scheduler with isolated failover (cron: ${cronExpression})`,
    };
}
